version: "3"

services:
  client:
    build: ./
    command: sh -c "yarn install && yarn run start"
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
